### PR TITLE
avatar done

### PR DESCRIPTION
**Pull request by srishtigautam21**
Made the avatar component and did some documentation changes.

### CODE REVIEW

**Review by zoef-yt — APPROVED** [review]
Looks good for merge.

**Review by iRohitGaur — COMMENTED** [review]
Looks great. Good to merge.

**Review by amartya-rs — APPROVED** [review]
You can give some extra spacing for better clarity of code. Rest looks good to me.

**Comment by srishtigautam21** [comment]
> You can give some extra spacing for better clarity of code. Rest looks good to me.

ok

**Pull request merged**
